services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - app_network
      - db_network
    # DB HEALTHY না হওয়া পর্যন্ত অপেক্ষা করবে
    depends_on:
      db:
        condition: service_healthy 
      nginx: # Nginx এর উপর নির্ভর করার প্রয়োজন নেই, তবুও কনফিগারেশন সঠিক
        condition: service_started

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      backend:
        condition: service_started
    networks:
      - app_network   

  db:
    image: mysql:8
    container_name: mysql_db_prod
    restart: always
    environment:
      # 🚨 নতুন ভ্যারিয়েবল যোগ করা হয়েছে: Laravel এর ইউজার ও পাসওয়ার্ড
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME} # DB_USERNAME ব্যবহার করুন
      MYSQL_PASSWORD: ${DB_PASSWORD} # DB_PASSWORD ব্যবহার করুন
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network
    healthcheck:
      # 🚨 healthcheck এ ইউজারনেম ও পাসওয়ার্ড যোগ করা হলো
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s 

networks:
  app_network:
  db_network:

volumes:
  db_data: