services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - app_network
      - db_network
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      backend:
        condition: service_started
    networks:
      - app_network   

  db:
    image: mysql:8
    container_name: mysql_db_prod
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s   # প্রতি 10 সেকেন্ড পর চেক করবে
      timeout: 5s     # 5 সেকেন্ডের মধ্যে উত্তর না পেলে ব্যর্থ
      retries: 5      # 5 বার ব্যর্থ হলে 'unhealthy'
      start_period: 30s # প্রথম 30 সেকেন্ড অপেক্ষা করবে

networks:
  app_network:
  db_network:

volumes:
  db_data:
