services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=app_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app_network
      - db_network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    container_name: react_app
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - app_network
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db_network
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - db_network

networks:
  app_network:
  db_network:

volumes:
  db_data:
