services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - app_network
      - db_network
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - backend
    networks:
      - app_network   

  db:
    image: mysql:8
    container_name: mysql_db_prod
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network

networks:
  app_network:
  db_network:

volumes:
  db_data:
